export enum Payout {
  NATURAL_ROYAL_FLUSH = 800,
  FOUR_DEUCES = 200,
  WILD_ROYAL_FLUSH = 25,
  FIVE_OF_A_KIND = 15,
  STRAIGHT_FLUSH = 9,
  FOUR_OF_A_KIND = 5,
  FULL_HOUSE = 3,
  FLUSH = 2,
  STRAIGHT = 2,
  THREE_OF_A_KIND = 1,
  DEFAULT = 0,
}
