on: workflow_dispatch
name: Deploy MF Video Poker
jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install from cache first
        uses: actions/cache@v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}

      - name: NPM Build
        run: |
          yarn install
          npm run build
        env:
          CI: false

      - name: Set up gCloud auth
        uses: google-github-actions/auth@v1
        with:
          project_id: mf-video-poker
          credentials_json: ${{ secrets.GCLOUD_CREDENTIALS_JSON }}

      - name: Set up gCloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: mf-video-poker

      - name: Deploy app to GCP
        run: npm run deploy
